'use strict';

module.exports = {
  POLL_SERVER: 'POLL_SERVER',
  UPDATE_CURRENT_INDEX: 'UPDATE_CURRENT_INDEX',
  UPDATE_CURRENT_TRACK: 'UPDATE_CURRENT_TRACK',
  UPDATE_ELAPSED: 'UPDATE_ELAPSED',
  UPDATE_PLAYBACK_STATE: 'UPDATE_PLAYBACK_STATE',
  UPDATE_TRACKS: 'UPDATE_TRACKS',
};
