'use strict';

module.exports = {
  UPDATE_CURRENT_INDEX:   'UPDATE_CURRENT_INDEX',
  UPDATE_CURRENT_TRACK:   'UPDATE_CURRENT_TRACK',
  UPDATE_ELAPSED:         'UPDATE_ELAPSED',
  UPDATE_PLAYBACK_STATE:  'UPDATE_PLAYBACK_STATE',
  UPDATE_PLAYLIST_TRACKS: 'UPDATE_PLAYLIST_TRACKS',
};
