'use strict';


module.exports = {
  PLAYBACK_TOGGLE: 'PLAYBACK_TOGGLE',

  PLAYLIST_ADD_SONG: 'PLAYLIST_ADD_SONG',
  PLAYLIST_MOVE_SONG: 'PLAYLIST_MOVE_SONG',
  PLAYLIST_REMOVE_SONG: 'PLAYLIST_REMOVE_SONG',

  SEARCH_CHANGE: 'SEARCH_CHANGE',
  SEARCH_TOGGLE: 'SEARCH_TOGGLE',
};
